name: Test

on:
  push:
    branches: [ "5.0" ]
  pull_request:
    branches: [ "5.0" ]

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          docker build -t mysql:latest -f docker/mysql/Dockerfile .
          docker build -t phpunit:latest -f docker/phpunit/Dockerfile .

      - name: Create network
        run: docker network create -d bridge lf-tests

      - name: Bring up MySQL service
        run: docker run -d --name lf-tests-mysql --network lf-tests --mount type=tmpfs,destination=/var/lib/mysql mysql:latest

      - name: Run Composer install
        run: docker run -v "$(pwd):/app" composer:2.0.3 install

      - name: Run PHPUnit
        run: docker run -v "$(pwd):/app" --network lf-tests phpunit:latest