name: Tests

on:
  push:
    branches: [ "6.x" ]
  pull_request:
    branches: [ "6.x" ]

jobs:
  run:
    name: Run PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bring up MySQL service
        run: docker compose up -d mysql
      - name: Run Composer install
        run: docker compose run composer install
      - name: Run PHPUnit
        run: docker compose run phpunit
